### ISSUE TITLE
Incorrect portlet dll name in import files

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-workflow#5]
Workflow portlet import files contain an incorrect (old) library name: _SenseNet.CorePortlets_. This prevents portal builders add workflow portlets to pages.

The correct name is: **SenseNet.Workflow.Portlets**

Folder to fix files in: _/src/nuget/snadmin/install-workflow/import-pages/Portlets/Workflow_
 
https://github.com/SenseNet/sn-workflow/tree/master/src/nuget/snadmin/install-workflow/import-pages/Portlets/Workflow

**Comment by dotslash21** [comment]
Hi! I'd like to take on this issue for the hacktoberfest challenge. Just to confirm my understanding, I just need to replace all of the instances of "SenseNet.CorePortlets" to "SenseNet.Workflow.Portlets" on the files under the "/src/nuget/snadmin/install-workflow/import-pages/Portlets/Workflow" folder right?
